name: User Story
description: Create a user story that adheres to the INVEST principles.
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        Make sure user stories follow the INVEST principles:
        **I**ndependent, **N**egotiable, **V**aluable, **E**stimable, **S**mall, **T**estable.
  
  - type: textarea
    id: story-text
    attributes:
      label: User Story
      description: "Format: As a [persona], I want [action], so that [value]. (Max 2 sentences)"
      placeholder: "As a user, I want to..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the criteria that must be met for this story to be 'Done'. (You can add or edit rows below)"
      value: |
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, links, or technical constraints.
    validations:
      required: false
