spring.application.name=backend
spring.main.banner-mode=off
spring.jpa.properties.hibernate.search.backend.directory.root=./lucene-indexes
spring.jpa.properties.hibernate.search.backend.analysis.configurer=class:de.udezeug.backend.config.CustomAnalysisConfigurer